services:
  database:
    image: postgres:18
    env_file:
      - ./backend/.env
    container_name: postgress_db
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - database

volumes:
  pgdata:

