/**
 * Gives the website what it needs from here, so the two can't drift apart:
 * its content types, generated from the page schemas, and the content
 * snapshot it shows when the API can't be reached.
 *
 *   bun run site:export ../../uni-cms/src/content
 *
 * Re-run it after changing a template in src/site-content/templates.
 */
import { cpSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { PAGES, TEMPLATES } from '../src/site-content/pages';
import type { Field } from '../src/site-content/schema/fields';
import { ICONS } from '../src/site-content/templates/icons';

const pascal = (key: string) =>
  key.replace(/(^|-)(\w)/g, (_, __, c: string) => c.toUpperCase()) + 'Content';

const indent = (text: string, depth: number) =>
  text.replace(/\n/g, `\n${'  '.repeat(depth)}`);

function typeOf(field: Field, depth = 0): string {
  switch (field.type) {
    case 'text':
      return 'Localized';
    case 'string':
    case 'image':
    case 'file':
      return 'string';
    case 'number':
      return field.optional ? 'number | null' : 'number';
    case 'boolean':
      return 'boolean';
    case 'choice': {
      const values = field.options.map((o) => o.value);
      const isIcons =
        values.length === ICONS.length &&
        ICONS.every(([v]) => values.includes(v));
      return isIcons
        ? 'IconName'
        : values.map((v) => JSON.stringify(v)).join(' | ');
    }
    case 'group': {
      const lines = Object.entries(field.fields).map(([key, child]) => {
        const doc = `/** ${child.label.en} */\n`;
        return `${doc}${JSON.stringify(key).replace(/^"([A-Za-z_]\w*)"$/, '$1')}: ${typeOf(child, depth + 1)};`;
      });
      return `{\n  ${indent(lines.join('\n'), 1)}\n}`;
    }
    case 'list': {
      const item = typeOf(field.item, depth);
      return /^[\w|" -]+$/.test(item) && !item.includes('|')
        ? `${item}[]`
        : `Array<${item}>`;
    }
  }
}

const out = [
  '// Generated by backend/scripts/site-types.ts from the page schemas. Do not edit by hand.',
  '',
  '/** Text in both website languages; either half may be empty. */',
  'export interface Localized {\n  ar: string;\n  en: string;\n}',
  '',
  `/** The icons a content manager may pick; src/content/icons.tsx draws each. */`,
  `export type IconName =\n  | ${ICONS.map(([v]) => JSON.stringify(v)).join('\n  | ')};`,
  '',
  ...Object.entries(TEMPLATES).map(
    ([key, schema]) =>
      `/** ${schema.label.en} */\nexport type ${pascal(key)} = ${typeOf(schema)};\n`,
  ),
  '/** Every page of the website, by key, with the content it holds. */',
  `export interface PageContents {\n${PAGES.map((p) => `  ${JSON.stringify(p.key)}: ${pascal(p.template)};`).join('\n')}\n}`,
  '',
  'export type PageKey = keyof PageContents;',
  '',
];

const target = process.argv[2];
if (!target)
  throw new Error('usage: bun run site:export <website content directory>');
writeFileSync(join(target, 'generated.ts'), out.join('\n'));
rmSync(join(target, 'snapshot'), { recursive: true, force: true });
cpSync(
  join(__dirname, '..', 'seed', 'site-content', 'pages'),
  join(target, 'snapshot'),
  { recursive: true },
);
console.log(
  `wrote ${target}/generated.ts and ${target}/snapshot/ (${PAGES.length} pages)`,
);
